[package]
name = "rustunumic-cli"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities"]

[dependencies]
dotenv-vault = "0.1.1"

[dev-dependencies]

[build-dependencies]

[[bin]]
name = "rustunumic"
path = "src/main.rs"
doc = false
