[package]
name = "rustunumic-cli"
version = "0.1.0"
edition = "2024"
categories = ["command-line-utilities"]

[dependencies]
dotenvy = "0.15"

[dev-dependencies]

[build-dependencies]

[[bin]]
name = "rustunumic"
path = "src/main.rs"
doc = false
